"""
schemas/rag.py
--------------
Pydantic schemas for the Cipherix RAG (Retrieval-Augmented Generation) API.
"""

from typing import Optional

from pydantic import BaseModel, Field


class RAGRequest(BaseModel):
    """Payload for a vault-isolated RAG query."""

    vault_id: str = Field(
        ...,
        description="UUID of the authorized target vault to query against.",
        json_schema_extra={"example": "123e4567-e89b-12d3-a456-426614174000"},
    )
    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Natural language question to answer from vault documents.",
        json_schema_extra={"example": "What encryption algorithm does Cipherix use?"},
    )
    top_k: Optional[int] = Field(
        default=None,
        ge=1,
        le=20,
        description="Maximum number of chunks to retrieve for context (default: rag_max_chunks).",
        json_schema_extra={"example": 5},
    )
    min_similarity: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Minimum cosine similarity for a chunk to be included in context (default: rag_min_similarity).",
        json_schema_extra={"example": 0.3},
    )


class RAGSource(BaseModel):
    """Source citation for a single document chunk used in a RAG answer."""

    document_id: str = Field(..., description="UUID of the source document.")
    filename: Optional[str] = Field(default=None, description="Original filename of the source document.")
    chunk_id: str = Field(..., description="Unique deterministic SHA-256 chunk identifier.")
    chunk_index: int = Field(..., description="0-indexed position of the chunk within the document.")
    page_number: Optional[int] = Field(default=None, description="Page number if extracted from a paginated file.")
    similarity: float = Field(..., description="Cosine similarity score between the query and this chunk (0.0–1.0).")


class RAGResponse(BaseModel):
    """Response containing a grounded LLM answer and source citations."""

    vault_id: str = Field(..., description="UUID of the queried vault.")
    query: str = Field(..., description="Echoed user query string.")
    answer: str = Field(..., description="Grounded answer generated by the local LLM.")
    sources: list[RAGSource] = Field(
        ...,
        description="Document chunks used to generate the answer, ordered by relevance.",
    )
    total_chunks_used: int = Field(..., description="Number of chunks included in the LLM context.")
    llm_model: str = Field(..., description="Ollama model name used for generation.")
